from tests_add_price_level import TestAddPriceLevel
from tests_add_to_observed import TestAddToObserved
from tests_delete_price_level import TestDeletePriceLevel
from tests_delete_observed import TestDeleteObserved
from tests_show_observed import TestShowObserved
from tests_show_price_levels import TestShowPriceLevels

TestAddPriceLevel
TestAddToObserved
TestDeletePriceLevel
TestDeleteObserved
TestShowObserved
TestShowPriceLevels